### PR TITLE
fix exact lctx elaborate handling. and register exists

### LINKED ISSUE #251: Exact input does not accept holes
apply does maybe refer to that

### PR DESCRIPTION
**Pull request by char3210**
exact argument holes can now refer to terms in the local context

### CODE REVIEW

File: test/automation/test_tactic_exact.ml [hunk 1]
```diff
@@ -20,11 +20,7 @@ let test_exact_wrong_type () =
   let st = start (t (Sort 0)) in
   match exact (t (Sort 0)) st with
   | Success _ -> Alcotest.fail "expected Failure but got Success"
-  | Failure msg ->
-      Alcotest.(check bool)
-        "message starts with 'exact:'"
-        true
-        (String.length msg >= 6 && String.sub msg 0 6 = "exact:")
+  | Failure _ -> ()
```
Comment (tlringer) [inline test/automation/test_tactic_exact.ml:23]: Just curious why this was changed, though if it's because it was too dependent on the error message, that is fine.

If you improved how `exact` functions, then adding a test that used to fail would be good. I'm also curious if you can look into #231 with this change. If you change `apply` in the relevant rewrite test back to `exact`, does it work with your changes? (It did not before them.)

**Comment by tlringer** [comment]
Also it would be good to separate the "register exists" thing into a tiny separate PR so we can just get that merged immediately

**Comment by tlringer** [comment]
Actually fine to merge due to urgency but will need to handle better testing at #242

**Review by tlringer — APPROVED** [review]
